### ISSUE TITLE
Why override `ExecutionContext` for ScalaTest?

### ISSUE THREAD

**Issue by hugo-vrijswijk** [typelevel/cats-effect-testing#106]
I couldn't find any links to a gitter or other question space so I figured I'd create an issue for my question.

ScalaTest provides its own `ExecutionContext` for `AsyncTestSuite`s (explained [here](https://www.scalatest.org/user_guide/async_testing) under 'Asynchronous execution model') which is a serial execution context. The relevant reason for this is:

> asynchronous-style tests need not be complete when the test body returns, because the test body returns a `Future[Assertion]`. This `Future[Assertion]` will often represent a test that has not yet completed. As a result, when using a more traditional execution context backed by a thread-pool, you could potentially start many more tests executing concurrently than there are threads in the thread pool. The more concurrently execute tests you have competing for threads from the same limited thread pool, the more likely it will be that tests will intermitently fail due to timeouts. 

 In this library the `ExecutionContext` is [overridden to the Scala global EC](https://github.com/djspiewak/cats-effect-testing/blob/master/scalatest/src/main/scala/cats/effect/testing/scalatest/AsyncIOSpec.scala#L25). What is the reasoning behind this? I can imagine there is a very good reason, but maybe there should be a comment explaining why?

The reason I am asking is because the global EC is causing issues for me in combination with [mockito-scala](https://github.com/mockito/mockito-scala) and its `AsyncMockitoSugar` which resets the mockito session after each test. Because the global EC will start tests in the same suite in parallel mockito-scala thinks that a previous test has not properly closed mocking, which will throw an exception and fail a bunch of tests semi-randomly. This is fixed when I make my own `AsyncIOSpec` which does not override the EC set by ScalaTest

**Comment by djspiewak** [comment]
I'd have to look back, but I imagine the reason it's being overridden is because the reasoning in the paragraph you quoted isn't particularly compelling. :-) In general, the right way to implement this sort of concern is a rate limiting on the number of tests being run, not a rate limiting *on the thread pool*. The paragraph is essentially making the argument that concurrency is bad, which… I'm not sure I buy.

With that said, the global EC is *also* usually quite bad, but for other reasons.

With all of *that* said, your use-case sounds like it really does need to be sequential. I don't know ScalaTest very well; I take it that it has no equivalent to Specs2's `sequential` scheduling strategy?

**Comment by fchaillou** [comment]
Hello,
I also had inconsistencies with my test runs with that, i also reverted to the scalatest default EC and it works "normally" with that change.

@djspiewak I agree with you that this is not really logical but i think that's the way scalatest implements async tests.
I would really love to migrate my code to another test framework but for now it will have to do :)

**Comment by hugo-vrijswijk** [comment]
From what I could tell ScalaTest's async test setup _depends_ on a synchronous EC, which is how it guarantees tests are run in serial. If you have that you don't need to build any fancy logic for waiting for previous async test results I suppose. I'm guessing this is maybe legacy code from when ScalaTest only had sync testing? I agree it's not a particularly good reason to have a synchronous EC. IMO if your production code is concurrent, your tests should be too (race conditions and all). 

ScalaTest _says_ it runs all tests in the same suite sequentially if you don't use [ParallelTestExecution](https://www.scalatest.org/scaladoc/3.2.2/org/scalatest/ParallelTestExecution.html) but apparently that's not the case when using async tests. In my opinion ScalaTest should have the same behaviour with sync and async tests of waiting for one test to finish before starting another. But that's outside of the scope for this issue and library.

For now  I've created my own copy of the AsyncIOSpec which leaves out the EC:

```scala
trait AsyncIOSpec extends AssertingSyntax with EffectTestSupport { asyncTestSuite: AsyncTestSuite =>
  implicit val ioContextShift: ContextShift[IO] = IO.contextShift(executionContext)
  implicit val ioTimer: Timer[IO] = IO.timer(executionContext)
}
```

**Comment by hugo-vrijswijk** [comment]
I think this library now uses the ScalaTest EC? Either way this has been explained to me, so I'll close this issue. Thank you for this wonderful library!
